name: venturecapital
favicon: null
layout_spectrum: 0.6081191604025662
typography_spectrum: 0.32788932765834033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8591972880531102
  lightness: 0.3200643905438483
  saturation: 0.7937853049952537
  rhythmicContrast: 0.8957545994780958
purpose: []
